---
title: "Glossary"
author: "Kristof Dorau"
date: '2021-02-09'
slug: null
draft: true
categories: []
tags:
- Fundamentals
- Glossary
subtitle: ''
summary: 'Important terminology to label the redox status of a soil'
authors: []
featured: no
image:
  caption: Photo by Patrick Tomasso on Unsplash
  focal_point: Smart
  preview_only: no
projects: []
---

*The post was last updated on `r format(Sys.Date(), "%Y-%m-%d")`.*

<style>
p.caption {
  font-size: 0.6em;
}
</style>


```{r echo = FALSE, message = FALSE}

knitr::opts_chunk$set(warning = F, echo = F, error = F, message = F)

library(tidyverse)
library(widgetframe)
library(timevis)
library(rmarkdown)
library(kableExtra)

## The theme must be in FRONT (!) of all ggplot or it will be overwritten
my_theme <- theme(
  panel.background = element_rect(fill = "white", color = "black"),
  panel.grid.major = element_blank(), 
  panel.grid.minor = element_blank(), 
  panel.border = element_blank())


```

```{r}

glossary <- readr::read_delim("glossary.csv", delim = ";")

glossary %>%
  arrange(Word) %>%
  kbl(caption = "Redox-related terminology for wetland soils") %>%
  kable_classic(full_width = T, html_font = "Cambria")


```

